#pragma once

#define ASSET_PATH "assets\\"
#define WINDOW_WIDTH 1200
#define WINDOW_HEIGHT 600
#define CANVAS_WIDTH 1000
#define CANVAS_HEIGHT 500
#define OBSTACLE_ROWS 4
#define OBSTACLES_PER_ROW 30
#define BALL_MOVEMENT 15.0f
#define INFOTEXT_SIZE 30
#define INFOTEXT_POSX 30
#define INFOTEXT_POSY 40
#define PI 3.14159265f

#define INFOSCREEN_WIDTH CANVAS_WIDTH / 4
#define INFOSCREEN_HEIGHT CANVAS_HEIGHT / 10

#define STARTSCREEN_WIDTH CANVAS_WIDTH / 3
#define STARTSCREEN_HEIGHT CANVAS_HEIGHT / 10

#define MENUSCREEN_WIDTH CANVAS_WIDTH / 2
#define MENUSCREEN_HEIGHT CANVAS_HEIGHT / 10